# This is a basic workflow to help you get started with Actions.
name: kubernetes-deploy

# Variables
env:
  KEY1: 'value1'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
on: 
  [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
   
    # Login to Docker Hub
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

#     # Runs a single command using the runners shell
#     - name: Deploy to Kubernetes
#       run: echo "Deploying to Kubernetes using ${{ env.KEY1 }}"
    
    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 900
        role-session-name: k8sInteg

    # Deploy to Kubernetes
    - name: Deploy to Kubernetes
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: get pods